#ifndef LLDPLOCPORTTABLE_OIDS_H
#define LLDPLOCPORTTABLE_OIDS_H
#include <sys/types.h>

#define LLDPLOCPORTTABLE_OID 1, 0, 8802, 1, 1, 2, 1, 3, 7
#define COLUMN_LLDPLOCPORTNUM 1
#define COLUMN_LLDPLOCPORTIDSUBTYPE 2
#define COLUMN_LLDPLOCPORTID 3
#define COLUMN_LLDPLOCPORTDESC 4

#define LLDPLOCPORTTABLE_MIN_COL COLUMN_LLDPLOCPORTNUM
#define LLDPLOCPORTTABLE_MAX_COL COLUMN_LLDPLOCPORTDESC
#endif