#ifndef LLDPSTATSRXPORTTABLE_OIDS_H
#define LLDPSTATSRXPORTTABLE_OIDS_H
#include <sys/types.h>

#define LLDPSTATSRXPORTTABLE_OID 1, 0, 8802, 1, 1, 2, 1, 2, 7
#define COLUMN_LLDPSTATSRXPORTNUM 1
#define COLUMN_LLDPSTATSRXPORTFRAMESDISCARDEDTOTAL 2
#define COLUMN_LLDPSTATSRXPORTFRAMESERRORS 3
#define COLUMN_LLDPSTATSRXPORTFRAMESTOTAL 4
#define COLUMN_LLDPSTATSRXPORTTLVSDISCARDEDTOTAL 5
#define COLUMN_LLDPSTATSRXPORTTLVSUNRECOGNIZEDTOTAL 6
#define COLUMN_LLDPSTATSRXPORTAGEOUTSTOTAL 7

#define LLDPSTATSRXPORTTABLE_MIN_COL COLUMN_LLDPSTATSRXPORTNUM
#define LLDPSTATSRXPORTTABLE_MAX_COL COLUMN_LLDPSTATSRXPORTAGEOUTSTOTAL
#endif