#ifndef LLDPREMUNKNOWNTLVTABLE_OIDS_H
#define LLDPREMUNKNOWNTLVTABLE_OIDS_H
#include <sys/types.h>

#define LLDPREMUNKNOWNTLVTABLE_OID 1, 0, 8802, 1, 1, 2, 1, 4, 3
#define COLUMN_LLDPREMUNKNOWNTLVTYPE 1
#define COLUMN_LLDPREMUNKNOWNTLVINFO 2

#define LLDPREMUNKNOWNTLVTABLE_MIN_COL COLUMN_LLDPREMUNKNOWNTLVTYPE
#define LLDPREMUNKNOWNTLVTABLE_MAX_COL COLUMN_LLDPREMUNKNOWNTLVINFO
#endif