#ifndef LLDPCONFIGMANADDRTABLE_OIDS_H
#define LLDPCONFIGMANADDRTABLE_OIDS_H
#include <sys/types.h>

#define LLDPCONFIGMANADDRTABLE_OID 1, 0, 8802, 1, 1, 2, 1, 1, 7
#define COLUMN_LLDPCONFIGMANADDRPORTSTXENABLE 1

#define LLDPCONFIGMANADDRTABLE_MIN_COL COLUMN_LLDPCONFIGMANADDRPORTSTXENABLE
#define LLDPCONFIGMANADDRTABLE_MAX_COL COLUMN_LLDPCONFIGMANADDRPORTSTXENABLE
#endif