#ifndef LLDPREMORGDEFINFOTABLE_OIDS_H
#define LLDPREMORGDEFINFOTABLE_OIDS_H
#include <sys/types.h>

#define LLDPREMORGDEFINFOTABLE_OID 1, 0, 8802, 1, 1, 2, 1, 4, 4
#define COLUMN_LLDPREMORGDEFINFOOUI 1
#define COLUMN_LLDPREMORGDEFINFOSUBTYPE 2
#define COLUMN_LLDPREMORGDEFINFOINDEX 3
#define COLUMN_LLDPREMORGDEFINFO 4

#define LLDPREMORGDEFINFOTABLE_MIN_COL COLUMN_LLDPREMORGDEFINFOOUI
#define LLDPREMORGDEFINFOTABLE_MAX_COL COLUMN_LLDPREMORGDEFINFO
#endif