#ifndef LLDPREMTABLE_OIDS_H
#define LLDPREMTABLE_OIDS_H
#include <sys/types.h>

#define LLDPREMTABLE_OID 1, 0, 8802, 1, 1, 2, 1, 4, 1
#define COLUMN_LLDPREMTIMEMARK 1
#define COLUMN_LLDPREMLOCALPORTNUM 2
#define COLUMN_LLDPREMINDEX 3
#define COLUMN_LLDPREMCHASSISIDSUBTYPE 4
#define COLUMN_LLDPREMCHASSISID 5
#define COLUMN_LLDPREMPORTIDSUBTYPE 6
#define COLUMN_LLDPREMPORTID 7
#define COLUMN_LLDPREMPORTDESC 8
#define COLUMN_LLDPREMSYSNAME 9
#define COLUMN_LLDPREMSYSDESC 10
#define COLUMN_LLDPREMSYSCAPSUPPORTED 11
#define COLUMN_LLDPREMSYSCAPENABLED 12

#define LLDPREMTABLE_MIN_COL COLUMN_LLDPREMTIMEMARK
#define LLDPREMTABLE_MAX_COL COLUMN_LLDPREMSYSCAPENABLED
#endif