#ifndef LLDPPORTCONFIGTABLE_OIDS_H
#define LLDPPORTCONFIGTABLE_OIDS_H
#include <sys/types.h>

#define LLDPPORTCONFIGTABLE_OID 1, 0, 8802, 1, 1, 2, 1, 1, 6
#define COLUMN_LLDPPORTCONFIGPORTNUM 1
#define COLUMN_LLDPPORTCONFIGADMINSTATUS 2
#define COLUMN_LLDPPORTCONFIGNOTIFICATIONENABLE 3
#define COLUMN_LLDPPORTCONFIGTLVSTXENABLE 4

#define LLDPPORTCONFIGTABLE_MIN_COL COLUMN_LLDPPORTCONFIGPORTNUM
#define LLDPPORTCONFIGTABLE_MAX_COL COLUMN_LLDPPORTCONFIGTLVSTXENABLE
#endif