#ifndef LLDPLOCMANADDRTABLE_OIDS_H
#define LLDPLOCMANADDRTABLE_OIDS_H
#include <sys/types.h>

#define LLDPLOCMANADDRTABLE_OID 1, 0, 8802, 1, 1, 2, 1, 3, 8
#define COLUMN_LLDPLOCMANADDRSUBTYPE 1
#define COLUMN_LLDPLOCMANADDR 2
#define COLUMN_LLDPLOCMANADDRLEN 3
#define COLUMN_LLDPLOCMANADDRIFSUBTYPE 4
#define COLUMN_LLDPLOCMANADDRIFID 5
#define COLUMN_LLDPLOCMANADDROID 6

#define LLDPLOCMANADDRTABLE_MIN_COL COLUMN_LLDPLOCMANADDRSUBTYPE
#define LLDPLOCMANADDRTABLE_MAX_COL COLUMN_LLDPLOCMANADDROID
#endif