#ifndef LLDPSTATSTXPORTTABLE_OIDS_H
#define LLDPSTATSTXPORTTABLE_OIDS_H
#include <sys/types.h>

#define LLDPSTATSTXPORTTABLE_OID 1, 0, 8802, 1, 1, 2, 1, 2, 6
#define COLUMN_LLDPSTATSTXPORTNUM 1
#define COLUMN_LLDPSTATSTXPORTFRAMESTOTAL 2

#define LLDPSTATSTXPORTTABLE_MIN_COL COLUMN_LLDPSTATSTXPORTNUM
#define LLDPSTATSTXPORTTABLE_MAX_COL COLUMN_LLDPSTATSTXPORTFRAMESTOTAL
#endif